import { Injectable } from '@nestjs/common';
import { CreateSandboxDto } from './dto/create-sandbox.dto';
import { UpdateSandboxDto } from './dto/update-sandbox.dto';
import { resolve } from 'path';

@Injectable()
export class SandboxService {
  async videoIaSandbox(createSandboxDto: CreateSandboxDto) {
    //Esperamos 10 segundos 
    await new Promise(resolve => setTimeout(resolve, 10000));
    return `
    Aquí tienes la transcripción detallada del video, identificando a los participantes y sus intervenciones:
\n\n**0:10-0:54**
\n\n**Secretaria:** Estado de México, siendo las diez horas del día 3 de diciembre de 2019, nos encontramos en la sala de audiencias número 1, a efecto de llevar a cabo la audiencia preliminar prevista en el artículo 873-E de la Ley Federal del Trabajo, relativo al expediente 1 de 2019, promovido por Juan Pérez en contra de la empresa Colp S.A. de C.V. La suscrita secretaria instructora hace constar la existencia de los medios tecnológicos necesarios que permiten audiovidiograbar la presente audiencia. Le solicitamos a los asistentes se pongan de pie a efecto de recibir al Juez Ortiz López quien va a presidir esta audiencia.\n\n**1:07-1:13**
\n\n**Juez:** Muy buenos días, tomen asiento, por favor.
\n\n**1:13-1:14**
\n\n**Abogado de la Parte Actora:** Buenos días.
\n\n**Abogado de la Parte Demandada:** Buenos días.
\n\n**1:15-3:32**
\n\n**Juez:** Muy bien, siendo el día 3 de diciembre del año 2019 y siendo las 10 con 15 horas, eh, en la ciudad de Toluca, Estado de México, damos por inicio a la audiencia preliminar del juicio entablado por Juan Pérez en contra de Colp S.A. de C.V., como un juicio laboral individual. Como bien saben, el día 1º de mayo del presente año, eh, se dio, se publicó la Ley Federal del Trabajo, con la cual eh se atendieron algunas reformas sustantivas en el en el Derecho Laboral Constitucional, lo cual instó a los poderes judiciales estatales a fin de que implementaran la Reforma Laboral desde los juzgados laborales tanto federales como estatales. Eh teniendo ustedes conocimiento de esto, es que se celebra bajo el nuevo modelo, eh, la audiencia de oralidad de este del juicio que se presenta ante esta jurisdicción el día de hoy. Eh, y bien, eh es preciso señalar que en términos del artículo 685, este procedimiento dentro del nuevo modelo del Derecho del Trabajo se rige bajo los principios de inmediatez, continuidad, celeridad, veracidad, concentración, economía y sencillez procesal. Asimismo, será público, gratuito y predominantemente oral y conciliatorio. En eh en en un estricto apego al Derecho a la Tutela Jurisdiccional Efectiva y verificando el principio de igualdad de partes, eh, solicito al trabajador y a su apoderado, se individualicen, por favor.
\n\n**3:32-3:59**
\n\n**Lic. Gilberto Chávez Orozco (Abogado de la Parte Actora):** Buenos días, Señoría, gracias. En este acto está presente el actor personalmente, Sr. Juan Pérez, quien ya se ha identificado previamente. Su servidor como su apoderado y representante legal, Licenciado Gilberto Chávez Orozco, con cédula profesional ya exhibida y cuya copia ya consta en autos. Muchas gracias.
\n\n**3:59-4:35**
\n\n**Lic. Álvaro Jesús Altamirano Ramírez (Abogado de la Parte Demandada):** De igual manera, solicito al apoderado legal de la empresa, así como a eh la directora de la misma que el día de hoy nos acompaña, se individualicen, por favor.
\n\n**Directora General de Colp S.A. de C.V.:** ¿Cómo no, Señoría? Con mucho gusto. Tenemos aquí a la Directora General de la compañía Colp, quien ha acreditado su representación y personalidad en términos del testimonio notarial que se ha exhibido. Y la señorita Gabriela Ramírez, quien nos va a estar acompañando, eh, esta mañana. Y su servidor, Álvaro Jesús Altamirano Ramírez, con cédula profesional 122539, debidamente también exhibida en el expediente, Señoría.
\n\n**4:40-5:20**
\n\n**Juez:** Muy bien, muchas gracias. Eh, una vez, eh, realizados por parte de la Secretaria Instructora, eh, en atención a mi instrucción, eh, la verificación de los medios tecnológicos necesarios que permiten audiovidiograbar la presente audiencia, y una vez verificada la asistencia de las partes llamadas a juicio, le pediría también a la Secretaria Instructora que de ser así, verifique si dentro de la sala de audiencia se encuentra algún funcionario público de la institución y eh conste su identificación.
\n\n**5:20-5:44**
\n\n**Secretaria:** Se encuentra el licenciado Gilberto Chávez Orozco, así como también la identificación del licenciado Álvaro Altamirano. [Ininteligible]. La Secretaria Instructora, Sara Pérez.
\n\n**Juez:** Muchas gracias.
\n\n**5:44-7:23**
\n\n**Juez:** Eh, bueno, de ser así y de contar con todos los elementos legales, daríamos inicio a la audiencia preliminar de el caso que se presenta ante esta jurisdicción. Como bien saben, eh, las partes en el juicio, y si no lo saben, les hago conocimiento de lo mismo, eh, la audiencia preliminar tiene por objeto depurar el procedimiento y resolver las excepciones dilatorias planteadas por las partes. Establecer los hechos no controvertidos, admitir o desechar las pruebas ofrecidas por las partes, según sea el caso, citar para audiencia de juicio y resolver el recurso de reconsideración contra los actos u omisiones del Secretario Instructor. Y dando seguimiento puntual a estos, a estos elementos de procedibilidad que establece la propia Ley, eh, tenemos, eh, como bien se desprende de los autos que integran el expediente de la etapa escrita del presente juicio, eh, que las partes en el presente juicio son Juan Pérez en contra de Colp S.A. de C.V. En este juicio, eh, como bien saben y conocen, eh, el actor demanda a la moral Colp S.A. de C.V., eh, un despido injustificado. Eh, atendiendo a los hechos planteados por las partes, por el actor y por el apoderado de la demandada, advertimos que en el hecho A, eh, no existe hecho controvertido alguno, toda vez que al dar contestación al hecho A, la parte demandada, acepta y reconoce la existencia de la relación laboral.
\n\n**7:23-9:38**
\n\n**Juez:** Asimismo, reconoce el puesto que ocupaba y las funciones del mismo, así como el salario que percibía de 25,000 pesos brutos, como parte de retribución a sus funciones. Asimismo, se reconoce la eh, el objeto social de la empresa, y eh, en estos términos, encuentro, perdón, que no existe, encuentro, perdón, que no existe eh, hecho controvertido al respecto en el hecho A. Eh, en el hecho B, eh, señala el actor que siempre se distinguió por la calidad de su trabajo, la puntualidad en sus jornadas y funciones, y que desempeñó sus labores eh de lunes a viernes en un horario de 9 a 18 horas. Eh, sin tener horario para tomar alimentos fuera de la fuente de trabajo, y e incluso eh que laboró en tiempo extraordinario hasta las 10 de la noche todos los días de la semana.
\n\n**9:38-12:18**
\n\n**Juez:** Eh, al dar contestación a este hecho, el demandado, o el apoderado del demandado, eh, reconoce eh la jornada de trabajo, omite realizar alguna defensa respecto de la calidad y puntualidad en las funciones que desempeñó el trabajador, y sí eh niega que este no contara con un horario para tomar alimentos, y asimismo niega la existencia del horario extraordinario de trabajo. Finalmente, en el hecho C, eh, señala el actor que sin mediar causa previa o justificada alguna, el día 31 de agosto de la anualidad a las 9 horas, en en el lugar de trabajo, en el lugar de la fuente de trabajo, ubicada en Avenida Pino Suárez número 201, primer piso, interior 3, aquí en el Estado de de México, en la ciudad de Toluca, eh, el guardia de seguridad eh por instrucciones del Jefe de Capital Humano, le comunicó, le prohibió el acceso y le comunicó que ya no laboraba más dentro de la empresa, por lo que en cuanto a las prestaciones eh, solicita eh, el reconocimiento del despido injustificado, acusa eh, como consecuencia de este, el pago de la indemnización constitucional, así como el pago de salarios caídas, caídos y demás prestaciones accesorias. Eh, al dar contestación el la parte demandada a este hecho, eh, niega la existencia de los mismos, señalando que este se desempeñó eh en una relación de carácter temporal bajo la modalidad de obra determinada, la cual eh se tuvo por concluida, eh, asimismo señaló que le pagó todas y cada una de las prestaciones devengadas, eh, no siendo así, el pago de las prestaciones accesorias generadas con motivo del de la conclusión de la relación laboral, eh para que finalmente, eh, este es este consigna eh el título de crédito respectivo a fin de que sea cobrado por la parte que se queja del despido. Eh, esta jurisdicción advierte que derivado del hecho C y de la contestación al mismo, existe una incongruencia. A fin de verificar en favor del trabajador el Derecho a la Tutela Jurisdiccional Efectiva, concretamente el Derecho de Acceso a la Justicia y el Debido Proceso, eh, es necesario preguntar al trabajador y su apoderado, si tienen conocimiento de que el día señalado eh, corresponde a un día inhábil, y si desean realizar alguna manifestación o aclaración al respecto.
\n\n**12:18-12:51**
\n\n**Lic. Gilberto Chávez Orozco (Abogado de la Parte Actora):** Sí, su Señoría, gracias. Efectivamente, el día 31 de agosto del 2019 es sábado. No obstante lo cual se confirma esa fecha como la del despido, dado que a pesar de que no era un día laborable, fue citado por parte de del representante de la empresa para realizar labores extraordinarias. Ya la Corte resolvió que el hecho de que sea el despido en un día inhábil no pugna con la existencia y procedencia del mismo. Quiero aprovechar la circunstancia, si usted me lo permite, para también plantear que en ese mismo sentido que usted plantea del recurso judicial efectivo,
\n\n**12:51-14:09**
\n\n**Lic. Gilberto Chávez Orozco (Abogado de la Parte Actora):** Queremos también plantear el recurso de reconsideración en contra de la omisión de el Secretario Instructor de este Juzgado, dado que al admitir la demanda, omitió prevenir a la parte actora para que la entablara adecuadamente, dado que del escrito de demanda se aprecia que hay horas extras, de 9 a 6, de 9 de la mañana a 6 de la tarde son 9 horas corridas y como el trabajador no tenía horario para salir a tomar sus alimentos, de ahí una sería diaria extra, dado que rebasaría las 8 horas máximas. Y adicionalmente, también se precisa que es salía a las 10 de la noche de manera cotidiana. Y de los recibos de pago de salarios que se exhibieron como prueba, se aprecia que no aparece cubierto el pago de horas extras. Luego entonces, debió de haberse prevenido a la parte actora para que atara su demanda en ese sentido y en todo caso integrar, o integrara su demanda con el reclamo de horas extras. Es cuanto, su Señoría.
\n\n**14:09-15:20**
\n\n**Juez:** Muchas gracias. Se, eh, se toman, eh, nota de las manifestaciones realizadas por la parte actora y al fin de privilegiar la equidad e igualdad entre las partes, eh, se le hace vigente el Derecho de Réplica a la contraparte, si es que es su deseo realizar alguna manifestación.
\n\n**Lic. Álvaro Jesús Altamirano Ramírez (Abogado de la Parte Demandada):** Por supuesto, Señoría, muchas gracias. En primer lugar, efectivamente el día 31 de agosto del 2019 es sábado. Eh, el señor Juan Pérez aquí presente, eh, no tenía absolutamente ninguna actividad los días sábado. Por lo tanto, pues es totalmente falso un supuesto despido que además en la demanda imputa al Jefe de Capital Humano sin precisar nombre y apellido. Y nos deja con un total estado de indefensión al no saber a qué persona se refiere. Su abogado acaba de mencionar, eh, también que un representante de la compañía llevó a cabo el despido sin precisar nombre y apellido. Aquí tenemos a la Directora General de la empresa, Gabriela Ramírez, y por supuesto, ella tampoco tiene conocimiento de que se hubiera presentado Juan Pérez ese día y a esa hora, y ante quién se presentó, lo cual pues hace muy complicado poder tener una defensa adecuada ante esa oscuridad.
\n\n**15:21-17:23**
\n\n**Lic. Álvaro Jesús Altamirano Ramírez (Abogado de la Parte Demandada):** En relación a las, a las horas extras, yo quisiera precisar que efectivamente elaboraba de 9 a 6 de la tarde, eh, de lunes a viernes, lo cual si sumamos nos da 45 horas, 9 por 5 son 45. Juan Pérez gozaba de media hora para descansar y tomar sus alimentos. Por lo tanto, si consideramos, vamos a pensar que si no salía de la fuente de trabajo, y de acuerdo a la jurisprudencia esa media hora se toma como tiempo efectivamente laborado. De cualquier manera no excedía la jornada de 48 horas a la semana, que es la máxima prevista para una jornada diurna de parte de un trabajador. Y obviamente es totalmente falso que hubiera trabajado después de las 6 de la tarde como él lo precisa. Para esto, eh, yo quisiera, eh, acompañar también al expediente, eh, dos elementos de prueba, su Señoría, uno que es pues los controles de asistencia, eh, de Juan Pérez en la compañía por un lapso de un año anterior a la fecha en la que supuestamente plantea un despido, y además de esto, pues el contrato de trabajo claramente establecido por obra determinada, firmado el 1º de enero del 2018, que establece como fecha de término muy precisa, justamente el día eh, 31 de agosto del presente año. Por lo tanto, eh, yo quisiera presentar estos dos documentos, eh, como una prueba, eh, documental para consideración y su mejor juicio, su Señoría, en la solución de este conflicto. Si me permite, aquí tengo los documentos.
\n\n**17:23-17:48**
\n\n**Lic. Álvaro Jesús Altamirano Ramírez (Abogado de la Parte Demandada):** [Se acerca a la Secretaria con documentos] Secretaria Instructora, por favor, encárguese de recibir los documentos y dar fe y cuenta de los documentos que está recibiendo.
\n\n**Secretaria:** [Recibe documentos] Doy cuenta de la recepción de los documentos que exhibe el licenciado Álvaro Altamirano.
\n\n**17:48-20:09**
\n\n**Juez:** Muchas gracias. De la misma forma, a fin de verificar eh el Derecho de Réplica y de igualdad y equidad de partes, eh, damos el, el uso de la voz al trabajador y a su apoderado a fin eh de realizar alguna manifestación, o si es que desea hacer uso de la voz para realizar alguna manifestación sobre el hecho concreto del ofrecimiento de los medios de prueba que acaba de exhibir el apoderado de la parte demandada.
\n\n**Lic. Gilberto Chávez Orozco (Abogado de la Parte Actora):** Sí, por favor, si me pudiera, me exhibiera el documento, si es tan amable. [Se acerca a la mesa para ver los documentos].
\n\n**Juez:** [A la Secretaria] Secretaria Instructora, por favor.
\n\n**Lic. Gilberto Chávez Orozco (Abogado de la Parte Actora):** Quisiera resaltar, señor Juez, que en primer lugar, no es una etapa de alegatos, y que las manifestaciones eh que externa mi contraparte sobre el día del despido, sobre las personas que eventualmente hayan despedido al trabajador, no es momento oportuno para realizarlas. Por otra parte, eh igual, en el tema de las horas extras, tampoco es este el momento para externar que haya gozado de algún tiempo para tomar alimentos. Y valga la pena recordar que los artículos 67 y 68 de la Ley Federal del Trabajo sí establecen la posibilidad de que se distribuya la jornada sabatina entre el resto de los días de la semana para que el trabajador pueda gozar de su descanso, ya sea de la totalidad o cuando menos medio día sábado. Pero ese no es un aspecto que se haya hecho valer en la contestación de la demanda, y que por ende debe quedar fuera de la litis de esta controversia. Respecto de la prueba documental que exhibe mi contraparte y que pretende ser incorporada como prueba, solicito respetuosamente sea desechada, dado que no es el momento procesal oportuno para hacerlo. La oportunidad para llevarlo a cabo fue al contestar la demanda, que es cuando tenía los elementos para poderla aportar.
    `;
  }

}
